#!/bin/bash
#SBATCH --job-name=taio_{dataset}
#SBATCH --cpus-per-task={cpus}
#SBATCH --output=slurm-{dataset}-%j.out
#SBATCH --time 5-0

source ~/.pyenv/versions/py310/bin/activate

python -m -v data_converter {dataset}
python -m classifier_pipeline --methods {methods} {dataset} --configs {configs} --test-length-fractions {test_length_fractions} -v
