#!/bin/bash
#SBATCH --job-name=taio_{name}
#SBATCH --cpus-per-task={cpus}
#SBATCH --output=slurm-{name}-%j.out
#SBATCH --time 1-0

source ~/.pyenv/versions/taioenv/bin/activate

python src/test_cases.py tests/{name}
