#!/bin/bash
#SBATCH --job-name=taio_{dataset}
#SBATCH --cpus-per-task={cpus}
#SBATCH --output=outputs/slurm-{dataset}-%j.out
#SBATCH --time 5-0

source ~/.pyenv/versions/py310/bin/activate

python -m data_converter -v {dataset}
python -m classifier_pipeline {dataset} --methods {methods} --configs {configs} --test-length-fractions {test_length_fractions} -v
